package com.mturk.tasks.futureDemo

/**
 * Created by Aimingnie on 7/25/15
 */
object FutureRules {

  val patternFuture2_6 = List(
    "ADJP < (JJ < likely|excited) < (S < (VP < TO < VP))",
    "S|VP|ADJP|ADVP < (IN|RB < about) $ (S < (VP < TO))",
    "S < (RB < about) < (VP < (TO < to))",
    "NP < (S < (VP < TO < VP))",
    "SBAR < WHNP|WHADVP < (S < (VP < TO))",
    "VP !< (__ < /seem|appear|happen|used|begin|began|love|like/) < (S < (VP < TO < VP))",
    "MD < will|'ll",
    "VP < (VB|VBG|VBP|VBZ|VBD|VBN < go|going|goes|went|gone) < (S < (VP < TO < VP))",
    "VBG < gon",
    "MD < wo",
    "MD < shall",
    "VP < ((MD < would|'d) $ (VP!<(VB<have|had)))",
    "VP < ((MD < may) $ (VP!<(VB<have|had)))",
    "VP < ((MD < might) $ (VP!<(VB<have|had)))",
    "VP < ((MD < should) $ (VP!<(VB<have|had)))",
    "MD < can",
    "MD < ca",
    "VP < ((MD< could) $ (VP!<(VB<have|had)))",
    "VP < ((MD< must) $ (VP!<(VB<have)))",
    "VP < (VB|VBD|VBG|VBN|VBP|VBZ < /need/) < (S < (VP < TO))",
    "VP < (VB|VBD|VBG|VBN|VBP|VBZ < /need/) < NP",
    "VP < (VB|VBD|VBG|VBN|VBP|VBZ < /hav|had|has/) < (S < (VP < TO))",
    "VP < (VBN < supposed) < (S < (VP < TO))",
    "VB|VBD|VBG|VBN|VBP|VBZ < /want/",
    "VBP < wan",
    "S < (NP $ (RB < better) $ VP)",
    "S < (NP $ (ADVP <<# better) $ VP)",
    "VP < (MD < /ought/) < (S < (VP < TO))",
    "VBG|JJ < upcoming",
    "VBG|JJ < pending",
    "VBN|JJ < /worr/",
    "VBN|JJ < excited",
    "ADJP < (JJ < due) !< (PP < TO)",
    "JJ < imminent",
    "JJ < future",
    "JJ < impending",
    "JJ < ready",
    "JJ < potential|possible",
    "JJ < eligible",
    "JJ < patient|impatient",
    "JJ < next",
    "RB < soon",
    "RB < ahead",
    "RB < sometime",
    "RB < potentially|possibly",
    "RB < finna|funna",
    "RB < patiently|impatiently",
    "NN|NNS < need",
    "NN|NNS << /hope/",
    "NN|NNS < /goal/",
    "NN|NNS < /choice/",
    "NN|NNS < /consequence/",
    "NN|NNS < /plan/",
    "NN|NNS < /schedule/",
    "NN|JJ < future",
    "NN|NNS < /due/",
    "NN|NNS < eligibility|eligibilities",
    "NN|NNS < fancy|fancies",
    "NN|NNS < ban|bans",
    "NN|NNS < /budget/",
    "NN|NNS < /deadline/",
    "NN|NNS < /expectation/",
    "NN|NNS < /guarantee/",
    "NN|NNS < /need/",
    "NN|NNS < necessity|necessities",
    "NN|NNS < /option/",
    "NN|NNS < possibility|possibilities",
    "NN|NNS < /will/",
    "NN|NNS < worry|worries",
    "NN|NNS < /ambition/",
    "VP < (MD < cant) < (VP < (VB < wait))",
    "VP < (MD < could) < (RB < n't|not) < (VP < (VB < wait))",
    "VP < (MD < can) < (RB < not) < (VP < (VB < wait))",
    "S < VP << /look/ << forward",
    "VB|VBD|VBG|VBN|VBP|VBZ << /hope|hoping/",
    "VB|VBD|VBG|VBN|VBP|VBZ < plan|plans|planned|planning",
    "VB|VBD|VBG|VBN|VBP|VBZ < /choos/",
    "VB|VBD|VBG|VBN|VBP|VBZ < /schedul/",
    "VB|VBD|VBG|VBN|VBP|VBZ < /consider/",
    "VP < (VB|VBD|VBG|VBN|VBP|VBZ < /figur/) < (PRT < (RP < out))",
    "VB|VBD|VBG|VBN|VBP|VBZ < /ban/",
    "VB|VBD|VBG|VBN|VBP|VBZ < fancy|fancies|fancying|fancied",
    "VB|VBD|VBG|VBN|VBP|VBZ < /guarantee/",
    "VB|VBD|VBG|VBN|VBP|VBZ < worry|worries|worrying|worried",
    "VB|VBD|VBG|VBN|VBP|VBZ < /expect/",
    "VB|VBD|VBG|VBN|VBP|VBZ < /envision/",
    "VB|VBD|VBG|VBN|VBP|VBZ < /anticipate/",
    "VB|VBD|VBG|VBN|VBP|VBZ < /predict/",
    "VB|VBD|VBG|VBN|VBP|VBZ < /foresee/",
    "VB|VBD|VBG|VBN|VBP|VBZ < /await/",
    "VB|VBD|VBG|VBN|VBP|VBZ < /doom/",
    "NN|RB < tomorrow",
    "(for, (time !, good|bad|right|best)) !<< VBD!<< (VP [ < (VB < have) | < (VBP [ < have | < 've ] ) | < (VBZ [ < has | < 's ] ) ] < (VP < VBN))",
    "NN|RB < tomorrow",
    "(for, (time !, good|bad|right|best)) !<< VBD!<< (VP [ < (VB < have) | < (VBP [ < have | < 've ] ) | < (VBZ [ < has | < 's ] ) ] < (VP < VBN))",
    "NP < (JJ < coming) < (NN|NNS|NNP < TN|TC)",
    "S <+ (!S) (PP < (IN < in|for) < (NP <, DT|CD|JJ < (NN|NNS|NNP < TN|TC))) !<< VBD !<< (VP [ < (VB < have) | < (VBP [ < have | < 've ] ) | < (VBZ [ < has | < 's ] ) ] < (VP < VBN))",
    "S <+ (!S) (PP  < (IN < on|for) < (NP < (NN|NNP|NNS < TN|TC))) !<< VBD !<< (VP [ < (VB < have) | < (VBP [ < have | < 've ] ) | < (VBZ [ < has | < 's ] ) ] < (VP < VBN))",
    "S <+ (!S) (ADVP < (NP < (NN|NNS|NNP < TN|TC)) < (RB < away)) !<< VBD !<< (VP [ < (VB < have) | < (VBP [ < have | < 've ] ) | < (VBZ [ < has | < 's ] ) ] < (VP < VBN))",
    "PP  < (IN < by) < (NP < (NN|NNS|NNP < TN|TC))",
    "PP  < (IN < by) < (NP < (DT < the|this)) !< past|last|previous < (NP < (NN|NNS|NNP < TN|TC))",
    "S <+ (!S) (RB < later) !<< VBD !<< (VP [ < (VB < have) | < (VBP [ < have | < 've ] ) | < (VBZ [ < has | < 's ] ) ] < (VP < VBN))",
    "S <+ (!S) (PP < (IN < at) < (NP < CD)) !<< VBD !<< (VP [ < (VB < have) | < (VBP [ < have | < 've ] ) | < (VBZ [ < has | < 's ] ) ] < (VP < VBN))",
    "PP  < (IN < by) < (NP < (DT < the|this)) < (NP < (NN|NNS|NNP < TN|TC))",
    "NP < (RB|JJ < Later|later) < (NN|NNP|NNS < TN)",
    "S <+ (!S) (VP < (NP < (NN|NNS|NNP < TN|TC))< (ADVP < (RB < away))) !<< VBD !<< (VP [ < (VB < have) | < (VBP [ < have | < 've ] ) | < (VBZ [ < has | < 's ] ) ] < (VP < VBN))",
    "(PP  < (IN < from) < (NP|ADVP < (RB < now)))",
    "S <+ (!S) (NP < ((DT < this) . (NN|NNS|NNP < TN|TC))) !<< VBD !<< (VP [ < (VB < have) | < (VBP [ < have | < 've ] ) | < (VBZ [ < has | < 's ] ) ] < (VP < VBN))",
    "S <+ (!S) PP < (IN < in) < (NP < (DT . (NN < couple))) . (PP < (IN < of) << TN|TC) !<< VBD !<< (VP [ < (VB < have) | < (VBP [ < have | < 've ] ) | < (VBZ [ < has | < 's ] ) ] < (VP < VBN))",
    "NP < (RBR|RB|JJ < later) < (DT < this)",
    "NP|VP < (NP|ADVP < ((RB|JJ < later) . (NP|NN|NNS < today)))",
    "NP < (JJ < next) < (NN|NNS|NNP < TN|TC)",
    "S <+ (!S) tonight !<< VBD !<< (VP [ < (VB < have) | < (VBP [ < have | < 've ] ) | < (VBZ [ < has | < 's ] ) ] < (VP < VBN))",
    "PP < (IN < by) &< (NP < (NP < DT) &< (PP << TN|TC))"
  )

  val patternPast = List(
    "VBD",
    "VP [ < ( VB < have ) | < ( VBP [ < have | < 've ] ) | < ( VBZ [ < has | < 's ] ) ] < ( VP < VBN )",
    "S < (when < VBD) <<  MD < would",
    "VP [ < ( VB [ < remember | < miss | < regret | < recall | < recollect ] ) | < ( VBP [ < remember | < miss | < regret | < recall | < recollect ] ) | < ( VBZ [ < remembers | < misses | < regrets | < recalls | < recollects ] ) ] < NP",
    "forgets|forgot|forgotten|forget !.to",
    "VP [ < ( VB < thank ) | < ( VBP < thank ) | < ( VBZ < thanks ) | < ( VBG < thanking ) ] < ( PP < ( IN < for ) )",
    "VP << wish|wishes|wished|wishing",
    "NP < ( JJ|NN < past )",
    "NP < ( NP < ( NNS [ < thanks | < congratulations | < congrats | < props | < kudos | < praise ] ) ) < ( PP < ( IN < for ) )",
    "NP << regret|regrets",
    "yesterday",
    "NP < (JJ < last) < (NN < week|weekend|month|year)",
    "NP < (JJ < last) < (NNS < weeks|weekends|months|years)",
    "proud . of|former|previous",
    "ago",
    "so.far"
  ) //16

}
